# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fOh1-EK-TzxtgkZi1tXZpCFsVWy6xWgs

# Librerías
"""

import pandas as pd
import numpy as np
# To plot a map
import geopandas as gpd
from shapely.geometry import Point, Polygon

"""# Carga de Datos"""

# Circuitos
circuitos = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/circuits.csv")
# Resultados Constructores
resultados_constructores = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/constructor_results.csv")
# Standings Constructores
standing_constructores = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/constructor_standings.csv")
# Constructores
constructores = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/constructors.csv")
# Standings Conductores
standing_conductores = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/driver_standings.csv")
# Conductores
coductores = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/drivers.csv")
# Tiempos de Vuelta
tiempos_vuelta = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/lap_times.csv")
# Pit-Stops
pit_stops = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/pit_stops.csv")
# Histórico Qualifying
historico_clasificacion = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/qualifying.csv")
# Histórico Carreras
historico_carreras = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/races.csv")
# Historico Resultados
historico_resultados = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/results.csv")
# Histórico Temporadas
historico_temporadas = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/seasons.csv")
# Historico Carreras Sprint
historico_sprint = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/sprint_results.csv")
# Glosario Estados de Carrera (finalizado, retirado, avería, etc.)
estados_carrera = pd.read_csv("https://raw.githubusercontent.com/tomipegu/f1_visualizations/Datasets/status.csv")

"""# Exploratory Data Analisis (EDA)

1. Evolucion Tiempos Por Vuelta
"""

# Los mejores tiempos de vuelta vienen reflejados en el archivo 'results.csv'
# 1) Extraemos el mejor tiempo de vuelta para cada conductor en cada carrera
# 2) Para una misma carrera, identificamos el mejor tiempode vuelta entre los conductores
# 3) Extraemos la información de circuito y año de cada carrerra 
# 4) Unificamos la información en una sola tabla

# Calculando la vuelta rapida de cada carrera
df_resultados = tiempos_vuelta[['raceId', 'driverId', 'milliseconds']]
df_fastest_lap = df_resultados.groupby(['raceId'], as_index = False)['milliseconds'].min()

# Determinando el circuito y el año de cada carrera
df_carreras = historico_carreras[['raceId', 'circuitId', 'year']]

# Unificamos la información en una sola tabla
df_races_and_laps = df_carreras.merge(df_fastest_lap)[['circuitId', 'year', 'milliseconds']]

# Para cada circuito, calculamos la diferencia relativa en los tiempos de 
# vuelta de cada año.

# 1) Ordenamos las entradas por circuto y fecha
df_races_and_laps.sort_values(by=['circuitId', 'year'], inplace=True)
# 2) Eliminamos filas con tiempos de vuelta inválidos
df_races_and_laps.drop(df_races_and_laps[df_races_and_laps['milliseconds'] == "\\N"].index, inplace = True)
# 3) Calculamos la diferencia relativa anual en los tiempos de vuelta de cada circuito
df_races_and_laps['delta'] = df_races_and_laps.groupby(['circuitId'], as_index = False)['milliseconds'].pct_change()
# 4) Eliminamos los valores null
df_races_and_laps.dropna(inplace = True)
# 5) Calculamos la variación media de cada año
df_yearly_delta = df_races_and_laps.groupby(["year"], as_index = False)['delta'].mean()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import matplotlib.pyplot as plt
import math

fig = plt.figure(figsize=(10, 8), dpi=80)
ax = plt.axes()
new_list = range(math.floor(min(df_yearly_delta['year'])), math.ceil(max(df_yearly_delta['year']))+1)
plt.xticks(new_list)


ax.plot(df_yearly_delta['year'].astype(int), df_yearly_delta['delta']);

df_yearly_delta

"""2. Circuitos 

"""

from google.colab import files
uploaded = files.upload()
map = gpd.read_file("World_Countries.shp")

# Let's convert latitudes and longitudes to points to plot them in the map
crs = {'init':'epsg:4326'}
geometry = [Point(xy) for xy in zip(circuitos['lng'], circuitos['lat'])]

geo_circuitos = gpd.GeoDataFrame(circuitos, crs = crs, geometry = geometry)
geo_circuitos.head()

fig,ax = plt.subplots(figsize=(15,15))
map.plot(ax=ax, alpha=0.4, color = "grey")
geo_circuitos[geo_circuitos['country'] == 'Spain'].plot(ax = ax, markersize = 20, color = "red", marker = "o", label= "Spain")
geo_circuitos[geo_circuitos['country'] != 'Spain'].plot(ax = ax, markersize = 20, color = "blue", marker = "o", label= "Else")
plt.legend(prop={'size':'15'})